Repository openshift/openshift-controller-manager, pull requests merged in 2019-10, with the labels that each got.

#32 Bug 1755115: handle multiple tags when scheduling image imports
  pkg/image/controller/scheduled_image_controller.go
  pkg/image/controller/scheduled_image_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#33 add leader lock for cluster-policy-controller upgrades
  pkg/cmd/controller/security.go
Labels: approved, lgtm, size/M

#34 Bug 1753731: seeding of img registry hostname with config if needed
  pkg/build/controller/build/build_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#38 Use StatefulSets apps/v1 api, v1beta1 is going to be dropped
  pkg/cmd/controller/image.go
Labels: approved, lgtm, size/XS

#37 remove quota, security controllers
  cmd/openshift-controller-manager/main.go
  pkg/cmd/controller/config.go
  pkg/cmd/controller/interfaces.go
  pkg/cmd/controller/quota.go
  pkg/cmd/controller/security.go
  pkg/quota/clusterquotareconciliation/reconciliation_controller.go
  pkg/quota/clusterquotareconciliation/reconciliation_controller_test.go
  pkg/quota/clusterquotareconciliation/workqueuebucket.go
  pkg/quota/quotaimageexternal/imagestreamimport_evaluator.go
  pkg/quota/quotaimageexternal/imagestreamimport_evaluator_test.go
  pkg/quota/quotaimageexternal/imagestreamtag_evaluator.go
  pkg/quota/quotaimageexternal/imagestreamtag_evaluator_test.go
  pkg/quota/quotaimageexternal/registry.go
  pkg/security/controller/namespace_scc_allocation_controller.go
  pkg/security/controller/namespace_security_allocation_controller_test.go
  pkg/security/controller/repair_test.go
  pkg/security/mcs/label.go
  pkg/security/mcs/label_test.go
  pkg/security/uidallocator/allocator.go
  pkg/security/uidallocator/allocator_test.go
Labels: approved, lgtm, size/XXL

#43 Bug 1764498: Remove references to extensions/v1beta1.
  pkg/template/controller/readiness.go
  pkg/template/controller/readiness_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#45 build: Report image registry host
  pkg/build/controller/build/build_controller.go
Labels: approved, lgtm, size/XS
