Repository openshift/openshift-controller-manager, pull requests merged in 2019-11, with the labels that each got.

#46 Bug 1755140: add build ca bundle to init containers
  pkg/build/controller/strategy/util.go
  pkg/build/controller/strategy/util_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#31 stops reading serving certs more than once
  pkg/cmd/controller/standalone_apiserver.go
  pkg/cmd/openshift-controller-manager/cmd.go
Labels: approved, lgtm, size/S

#48 Bug 1767218: Bug 1767219: don't enqueue non-existent buildconfigs for builds
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#42 Bug 1767047: add leader lock for cluster-policy-controller in scc_namespace_allocator controller
  pkg/cmd/controller/security.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M
