Repository openshift/openshift-controller-manager, pull requests merged in 2019-08, with the labels that each got.

#12 Builds - Mount trusted CA for cluster proxies
  pkg/build/buildutil/util.go
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/build/controller/strategy/util.go
Labels: approved, lgtm, size/L

#13 add event when a build references an input imagestreamtag local ref p…
  pkg/build/controller/build/build_controller.go
Labels: approved, lgtm, size/S

#16 Add Apps owners back
  pkg/apps/OWNERS
Labels: approved, lgtm, size/XS

#15 Bug 1741133: Fix DC adoption
  pkg/apps/deploymentconfig/deploymentconfig_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#17 enable global injection of mounted trust CAs
  pkg/build/buildutil/util.go
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/build/controller/strategy/custom_test.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti_test.go
  pkg/build/controller/strategy/util.go
  pkg/build/controller/strategy/util_test.go
Labels: approved, lgtm, size/M

#21 Bug 1730722: Add blocked registries to registries.conf
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
