Repository openshift/openshift-controller-manager, pull requests merged in 2019-07, with the labels that each got.

#2 Fix vendor
  Dockerfile
  Dockerfile.rhel
  vendor/github.com/docker/distribution/contrib/docker-integration/malevolent-certs/ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+client-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+client-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localhost-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localhost-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localregistry-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localregistry-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+client-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+client-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localhost-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localhost-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localregistry-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localregistry-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/tokenserver-oauth/certs/ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/tokenserver/certs/ca.pem
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/openshift/main.go
  vendor/k8s.io/kubernetes/third_party/etcd.BUILD
Labels: lgtm, size/L

#3 Install missing dependencies on OCP build
  Dockerfile.rhel
Labels: size/XS

#4 make local dockerfile consistent
  Dockerfile
Labels: approved, lgtm, size/XS

#6 Quickfix: revive legacyscheme
  cmd/openshift-controller-manager/main.go
Labels: approved, lgtm, size/S
