Repository openshift/openshift-controller-manager, pull requests merged in 2020-10, with the labels that each got.

#139 Bug 1884028: Update to use only k8s.io/klog/v2
  go.mod
  go.sum
  pkg/apps/deployer/deployer_controller.go
  pkg/apps/deployer/factory.go
  pkg/apps/deploymentconfig/controller_ref_manager.go
  pkg/apps/deploymentconfig/deploymentconfig_controller.go
  pkg/apps/deploymentconfig/factory.go
  pkg/apps/metrics/prometheus/metrics.go
  pkg/authorization/defaultrolebindings/defaultrolebindings.go
  pkg/build/buildutil/util.go
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/defaults/defaults.go
  pkg/build/controller/build/overrides/overrides.go
  pkg/build/controller/buildconfig/buildconfig_controller.go
  pkg/build/controller/common/util.go
  pkg/build/controller/policy/policy.go
  pkg/build/controller/policy/serial_latest_only.go
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/util.go
  pkg/build/metrics/prometheus/metrics.go
  pkg/client/genericinformers/interface.go
  pkg/cmd/controller/build.go
  pkg/cmd/controller/interfaces.go
  pkg/cmd/controller/serviceaccount.go
  pkg/cmd/controller/standalone_apiserver.go
  pkg/cmd/imageformat/imagetemplate.go
  pkg/cmd/openshift-controller-manager/cmd.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/image/controller/imagestream_controller.go
  pkg/image/controller/scheduled_image_controller.go
  pkg/image/controller/scheduler.go
  pkg/image/controller/signature/container_image_downloader.go
  pkg/image/controller/signature/signature_import_controller.go
  pkg/image/controller/trigger/image_trigger_controller.go
  pkg/image/metrics/prometheus/metrics.go
  pkg/image/trigger/buildconfigs/buildconfigs.go
  pkg/image/trigger/deploymentconfigs/deploymentconfigs.go
  pkg/project/controller/project_finalizer_controller.go
  pkg/route/ingress/ingress.go
  pkg/route/ingressip/service_ingressip_controller.go
  pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
  pkg/serviceaccounts/controllers/deleted_dockercfg_secrets.go
  pkg/serviceaccounts/controllers/deleted_token_secrets.go
  pkg/serviceaccounts/controllers/docker_registry_service.go
  pkg/template/controller/templateinstance_controller.go
  pkg/template/controller/templateinstance_finalizer.go
  pkg/unidling/controller/unidling_controller.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#134 Bug 1849176: Revert "Remove unnecessary yum install"
  Dockerfile
  Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#125 Add Build Result Counter Metric
  pkg/build/buildutil/util.go
  pkg/build/controller/build/build_controller.go
  pkg/build/metrics/prometheus/metrics.go
  pkg/build/metrics/prometheus/metrics_test.go
Labels: approved, lgtm

#140 Bug 1880357: Bump k8s.io packages
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/structuredmerge.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/k8s.io/apiserver/pkg/storage/errors.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
