Repository openshift/openshift-controller-manager, pull requests merged in 2020-01, with the labels that each got.

#60 Add ingress-to-route controller OWNERS
  pkg/route/OWNERS
Labels: approved, lgtm, size/S

#53 Bug 1760776: ingress: targetPortForService: Use port name only
  pkg/route/ingress/ingress.go
  pkg/route/ingress/ingress_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#58 Remove ServiceNetworkCIDR Config
  pkg/cmd/openshift-controller-manager/openshiftcontrolplane_default.go
Labels: approved, lgtm, size/XS
