Repository openshift/openshift-controller-manager, pull requests merged in 2020-06, with the labels that each got.

#114 Bug 1838372: Allow image push after postCommit script completes
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#110 pkg/image/controller/scheduler: Restore some logging
  pkg/image/controller/scheduler.go
Labels: approved, lgtm

#117 Bug 1832839: more changes required for named workqueue metrics on pre 1.18 k8s base
  pkg/apps/deployer/factory.go
  pkg/apps/deploymentconfig/factory.go
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/buildconfig/buildconfig_controller.go
  pkg/image/controller/signature/signature_import_controller.go
  pkg/metrics/workqueue.go
  pkg/project/controller/project_finalizer_controller.go
  pkg/route/ingressip/service_ingressip_controller.go
  pkg/unidling/controller/unidling_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#106 Bug 1819770: Removing yum commands from Dockerfile
  Dockerfile
  Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#116 Bug 1831888: StatefulSets v1 do not trigger on image changes
  pkg/cmd/controller/image.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
