Repository openshift/openshift-controller-manager, pull requests merged in 2020-09, with the labels that each got.

#132 [release-4.3] Bug 1849176: Allow image push after postCommit script completes
  Dockerfile
  Dockerfile.rhel
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#130 Bug 1820075: Reflect route status to ingress status
  pkg/cmd/controller/ingress.go
  pkg/route/ingress/ingress.go
  pkg/route/ingress/ingress_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#137 Bug 1862532: Fix label value validation for Builds
  pkg/build/buildutil/util.go
  pkg/build/buildutil/util_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
