Repository openshift/openshift-controller-manager, pull requests merged in 2020-03, with the labels that each got.

#69 Bug 1809699: Restore openshift-controller-manager metrics
  pkg/apps/metrics/prometheus/metrics.go
  pkg/apps/metrics/prometheus/metrics_test.go
  pkg/image/metrics/prometheus/metrics.go
  pkg/image/metrics/prometheus/metrics_test.go
  pkg/template/controller/metrics.go
  pkg/template/controller/metrics_test.go
  pkg/template/controller/readiness.go
  pkg/template/controller/templateinstance_controller.go
  pkg/template/controller/templateinstance_finalizer.go
  pkg/version/version.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#73 Bug 1813361: fix img reg ref on ICT if OCM knows img reg host before apiserver
  pkg/image/controller/trigger/image_trigger_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#64 [release-4.3] Bug 1802889: bump(github.com/mtrmac/gpgme): v0.1.2
  go.mod
  go.sum
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/github.com/mtrmac/gpgme/.travis.yml
  vendor/github.com/mtrmac/gpgme/data.go
  vendor/github.com/mtrmac/gpgme/go.mod
  vendor/github.com/mtrmac/gpgme/go_gpgme.c
  vendor/github.com/mtrmac/gpgme/go_gpgme.h
  vendor/github.com/mtrmac/gpgme/gpgme.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#77 Bug 1809862: report lastlogsnippet from init containers on failed/errored builds
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#82 Use Named Queues for Service Account Controller
  pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
  pkg/serviceaccounts/controllers/docker_registry_service.go
Labels: approved, lgtm
