Repository openshift/openshift-controller-manager, pull requests merged in 2020-12, with the labels that each got.

#145 Bug 1887745: Listing All Events with Chunking
  pkg/unidling/controller/unidling_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#150 BUILD-187: Detect if image trigger ID was cleared
  pkg/build/controller/buildconfig/buildconfig_controller.go
  pkg/build/controller/buildconfig/buildconfig_controller_test.go
  pkg/build/metrics/prometheus/metrics.go
  pkg/build/metrics/prometheus/metrics_test.go
Labels: approved, lgtm

#149 Bug 1860136: Fix for Annotation was not propagated to the route when changes made to existing ingress object
  pkg/route/ingress/ingress.go
  pkg/route/ingress/ingress_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
