Repository openshift/openshift-controller-manager, pull requests merged in 2020-04, with the labels that each got.

#84 Bug 1785023: Increase pull secrets controller QPS to 100
  pkg/cmd/controller/interfaces.go
  pkg/cmd/controller/serviceaccount.go
Labels: approved, bugzilla/valid-bug, lgtm

#92 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#83 Bug 1801415: Migrate extensions/v1beta1 -> networking.k8s.io/v1beta1
  pkg/cmd/controller/ingress.go
  pkg/route/ingress/ingress.go
  pkg/route/ingress/ingress_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#94 Bug 1815816: add 2 min retry on create build existing pod wrong owner (allow for GC)
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#96 Bug 1815816: more timing windows on build/pod owner ref correlation (allow GC to c…
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#95 Bug 1825324: Use named queues for all controllers
  pkg/apps/deployer/factory.go
  pkg/apps/deploymentconfig/factory.go
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/buildconfig/buildconfig_controller.go
  pkg/image/controller/signature/signature_import_controller.go
  pkg/project/controller/project_finalizer_controller.go
  pkg/route/ingressip/service_ingressip_controller.go
  pkg/unidling/controller/unidling_controller.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm
