Repository openshift/openshift-controller-manager, pull requests merged in 2020-05, with the labels that each got.

#98 Bug 1829863: update Dockerfile.rhel builder image to line up with art/brew/osbs
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#99 Bug 1831243: v1 StatefulSets do not trigger on image changes
  pkg/cmd/controller/image.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#103 Bug 1831245: StatefulSets v1 do not trigger on image changes
  pkg/cmd/controller/image.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#105 Bug 1829447: ensure build pod activeDeadlineSeconds always set
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/util.go
  pkg/build/controller/strategy/util_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#107 Bug 1809719: use ReleaseOnCancel for leader election config
  pkg/cmd/openshift-controller-manager/controller_manager.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#112 Bug 1829786: Allow scheduled retry of failed ImageStream import
  pkg/image/controller/scheduled_image_controller.go
  pkg/image/controller/scheduled_image_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#111 Bug 1832294: Add strategy metrics
  Makefile
  go.mod
  go.sum
  pkg/apps/deploymentconfig/factory.go
  pkg/apps/metrics/prometheus/metrics.go
  pkg/apps/metrics/prometheus/metrics_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
