Repository openshift/openshift-controller-manager, pull requests merged in 2021-09, with the labels that each got.

#194 Add OWNERS file to pkg/build
  pkg/build/OWNERS
Labels: lgtm, approved

#197 Bug 1977414: fail Build if ConfigMap or Secret does not exist
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/cmd/controller/build.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#201 Bug 2004203: BC ICT still must check spec last triggered image ID in case BC was last processed when cluster was pre 4.8
  pkg/image/controller/trigger/image_trigger_controller_test.go
  pkg/image/trigger/buildconfigs/buildconfigs.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#200 Bug 2004127: bump library-go and dependencies
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
