Repository openshift/openshift-controller-manager, pull requests merged in 2021-04, with the labels that each got.

#172 ingress: Migrate to networking.k8s.io/v1
  pkg/cmd/controller/ingress.go
  pkg/route/ingress/ingress.go
  pkg/route/ingress/ingress_test.go
Labels: approved, lgtm

#171 BUILD-186: build lastTriggeredID needs to be in status
  pkg/build/buildutil/util.go
  pkg/build/controller/buildconfig/buildconfig_controller_test.go
  pkg/image/controller/trigger/image_trigger_controller_test.go
  pkg/image/trigger/buildconfigs/buildconfigs.go
  pkg/image/trigger/buildconfigs/buildconfigs_test.go
Labels: approved, bugzilla/valid-bug, docs-approved, lgtm, px-approved, qe-approved

#176 Bug 1935165: fixed LANG for the builder container
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/custom_test.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, qe-approved
