Repository openshift/openshift-controller-manager, pull requests merged in 2022-08, with the labels that each got.

#235 Bug 2116715: remove GenericResourceInformer code because it is not used anymore
  pkg/client/genericinformers/interface.go
  pkg/cmd/controller/interfaces.go
  pkg/cmd/controller/route/interfaces.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#234 Bug 2117235: separate route controllers to a new command
  cmd/openshift-controller-manager/main.go
  cmd/route-controller-manager/main.go
  pkg/cmd/controller/route/apiserver_authenticator.go
  pkg/cmd/controller/route/apiserver_handlers.go
  pkg/cmd/controller/route/config.go
  pkg/cmd/controller/route/ingress.go
  pkg/cmd/controller/route/metrics.go
  pkg/cmd/controller/route/net.go
  pkg/cmd/controller/route/standalone_apiserver.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/route-controller-manager/cmd.go
  pkg/cmd/route-controller-manager/controller_manager.go
  pkg/cmd/route-controller-manager/openshiftcontrolplane_default.go
  pkg/cmd/routecontroller/route.go
  pkg/routeversion/version.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#236 Updating ose-openshift-controller-manager images to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
