Repository openshift/openshift-controller-manager, pull requests merged in 2024-04, with the labels that each got.

#292 OCPBUGS-31213: Unable to look up the service account secrets for build
  pkg/build/buildutil/util.go
  pkg/build/controller/build/build_controller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#298 OCPBUGS-32729: Rollback state of managed image pull secrets after downgrade.
  pkg/cmd/controller/pullsecrets.go
  pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller.go
  pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller_test.go
  pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller.go
  pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#301 TRT-1632: Revert #298 "OCPBUGS-32729: Rollback state of managed image pull secrets after downgrade."
  pkg/cmd/controller/pullsecrets.go
  pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller.go
  pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller_test.go
  pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller.go
  pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller_test.go
Labels: lgtm, approved, jira/valid-reference
