Repository openshift/openshift-controller-manager, pull requests merged in 2024-05, with the labels that each got.

#300 OCPBUGS-32729: Rollback state of managed image pull secrets after downgrade
  pkg/cmd/controller/pullsecrets.go
  pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller.go
  pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller_test.go
  pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller.go
  pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#297 OCPBUGS-30688: bump go-jose to fix CVE-2024-28176
  go.mod
  go.sum
  vendor/gopkg.in/go-jose/go-jose.v2/CHANGELOG.md
  vendor/gopkg.in/go-jose/go-jose.v2/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/asymmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/crypter.go
  vendor/gopkg.in/go-jose/go-jose.v2/encoding.go
  vendor/gopkg.in/go-jose/go-jose.v2/symmetric.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#302 OCPBUGS-33241: panic in image trigger controller
  pkg/image/trigger/annotations/annotations.go
  pkg/image/trigger/buildconfigs/buildconfigs.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#288 API-1644: Use bound service account tokens when generating pull secrets
  Dockerfile.rhel
  pkg/cmd/controller/config.go
  pkg/cmd/controller/imageregistry.go
  pkg/internalregistry/controllers/annotations.go
  pkg/internalregistry/controllers/image_pull_secret_controller.go
  pkg/internalregistry/controllers/keyid_observation_controller.go
  pkg/internalregistry/controllers/legacy_image_pull_secret_controller.go
  pkg/internalregistry/controllers/legacy_token_secret_controller.go
  pkg/internalregistry/controllers/registry_urls_observation_controller.go
  pkg/internalregistry/controllers/service_account_controller.go
Labels: lgtm, approved, jira/valid-reference

#305 OCPBUGS-33600: revert revert and fix for hypershift
  pkg/cmd/controller/config.go
  pkg/cmd/controller/imageregistry.go
  pkg/internalregistry/controllers/annotations.go
  pkg/internalregistry/controllers/image_pull_secret_controller.go
  pkg/internalregistry/controllers/keyid_observation_controller.go
  pkg/internalregistry/controllers/legacy_image_pull_secret_controller.go
  pkg/internalregistry/controllers/legacy_token_secret_controller.go
  pkg/internalregistry/controllers/registry_urls_observation_controller.go
  pkg/internalregistry/controllers/service_account_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#307 OCPBUGS-33834: filter delete events
  pkg/internalregistry/controllers/legacy_image_pull_secret_controller.go
  pkg/internalregistry/controllers/legacy_token_secret_controller.go
  pkg/internalregistry/controllers/registry_urls_observation_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#306 OCPBUGS-33815: openshift-controller-manager overwriting/undoing changes to ServiceAccount imagePullSecrets
  pkg/internalregistry/controllers/service_account_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only
