Repository openshift/openshift-controller-manager, pull requests merged in 2024-10, with the labels that each got.

#342 OCPBUGS-32869: replaces deprecated square/go-jose wtih go-jose/go-jose
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#337 OCPBUGS-42097: user system:serviceaccount:openshift-infra:serviceaccount-pull-secrets-controller in ns/openshift-infra must not produce too many applies
  pkg/internalregistry/controllers/service_account_controller.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#341 NO-JIRA: cleanup root and app OWNERS
  OWNERS
  pkg/apps/OWNERS
Labels: lgtm, approved, jira/valid-reference
