Repository openshift/openshift-controller-manager, pull requests merged in 2025-05, with the labels that each got.

#373 OCPBUGS-54695: Empty proxy variables are causing issues during the build
  go.mod
  go.sum
  pkg/build/controller/build/defaults/defaults.go
  vendor/go.uber.org/atomic/.codecov.yml
  vendor/go.uber.org/atomic/.gitignore
  vendor/go.uber.org/atomic/CHANGELOG.md
  vendor/go.uber.org/atomic/LICENSE.txt
  vendor/go.uber.org/atomic/Makefile
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/bool.go
  vendor/go.uber.org/atomic/bool_ext.go
  vendor/go.uber.org/atomic/doc.go
  vendor/go.uber.org/atomic/duration.go
  vendor/go.uber.org/atomic/duration_ext.go
  vendor/go.uber.org/atomic/error.go
  vendor/go.uber.org/atomic/error_ext.go
  vendor/go.uber.org/atomic/float32.go
  vendor/go.uber.org/atomic/float32_ext.go
  vendor/go.uber.org/atomic/float64.go
  vendor/go.uber.org/atomic/float64_ext.go
  vendor/go.uber.org/atomic/gen.go
  vendor/go.uber.org/atomic/int32.go
  vendor/go.uber.org/atomic/int64.go
  vendor/go.uber.org/atomic/nocmp.go
  vendor/go.uber.org/atomic/pointer_go118.go
  vendor/go.uber.org/atomic/pointer_go118_pre119.go
  vendor/go.uber.org/atomic/pointer_go119.go
  vendor/go.uber.org/atomic/string.go
  vendor/go.uber.org/atomic/string_ext.go
  vendor/go.uber.org/atomic/time.go
  vendor/go.uber.org/atomic/time_ext.go
  vendor/go.uber.org/atomic/uint32.go
  vendor/go.uber.org/atomic/uint64.go
  vendor/go.uber.org/atomic/uintptr.go
  vendor/go.uber.org/atomic/unsafe_pointer.go
  vendor/go.uber.org/atomic/value.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#380 OCPBUGS-52193: legacy image pull secret rollback controller
  pkg/cmd/controller/config.go
  pkg/cmd/controller/imageregistry.go
  pkg/cmd/controller/pullsecrets.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/internalregistry/controllers/rollback/legacy_image_pull_secret_rollback_controller.go
  pkg/internalregistry/controllers/rollback/legacy_image_pull_secret_rollback_controller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#377 OCPBUGS-55699: Empty proxy variables are causing issues during the build
  go.mod
  go.sum
  pkg/build/controller/build/defaults/defaults.go
  vendor/go.uber.org/atomic/.codecov.yml
  vendor/go.uber.org/atomic/.gitignore
  vendor/go.uber.org/atomic/CHANGELOG.md
  vendor/go.uber.org/atomic/LICENSE.txt
  vendor/go.uber.org/atomic/Makefile
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/bool.go
  vendor/go.uber.org/atomic/bool_ext.go
  vendor/go.uber.org/atomic/doc.go
  vendor/go.uber.org/atomic/duration.go
  vendor/go.uber.org/atomic/duration_ext.go
  vendor/go.uber.org/atomic/error.go
  vendor/go.uber.org/atomic/error_ext.go
  vendor/go.uber.org/atomic/float32.go
  vendor/go.uber.org/atomic/float32_ext.go
  vendor/go.uber.org/atomic/float64.go
  vendor/go.uber.org/atomic/float64_ext.go
  vendor/go.uber.org/atomic/gen.go
  vendor/go.uber.org/atomic/int32.go
  vendor/go.uber.org/atomic/int64.go
  vendor/go.uber.org/atomic/nocmp.go
  vendor/go.uber.org/atomic/pointer_go118.go
  vendor/go.uber.org/atomic/pointer_go118_pre119.go
  vendor/go.uber.org/atomic/pointer_go119.go
  vendor/go.uber.org/atomic/string.go
  vendor/go.uber.org/atomic/string_ext.go
  vendor/go.uber.org/atomic/time.go
  vendor/go.uber.org/atomic/time_ext.go
  vendor/go.uber.org/atomic/uint32.go
  vendor/go.uber.org/atomic/uint64.go
  vendor/go.uber.org/atomic/uintptr.go
  vendor/go.uber.org/atomic/unsafe_pointer.go
  vendor/go.uber.org/atomic/value.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#379 OCPBUGS-55826: Empty proxy variables are causing issues during the build
  pkg/build/controller/build/defaults/defaults.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#381 WRKLDS-1676: Delete unused pkg/serviceaccounts
  go.mod
  go.sum
  pkg/cmd/controller/pullsecrets.go
  pkg/internalregistry/controllers/service_account_controller.go
  pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
  pkg/serviceaccounts/controllers/deleted_dockercfg_secrets.go
  pkg/serviceaccounts/controllers/deleted_dockercfg_secrets_test.go
  pkg/serviceaccounts/controllers/deleted_token_secrets.go
  pkg/serviceaccounts/controllers/deleted_token_secrets_test.go
  pkg/serviceaccounts/controllers/docker_registry_service.go
  pkg/serviceaccounts/controllers/docker_registry_service_test.go
  pkg/serviceaccounts/controllers/mutation_cache.go
  pkg/serviceaccounts/controllers/pull_secrets.go
  pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller.go
  pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller_test.go
  vendor/github.com/hashicorp/golang-lru/.gitignore
  vendor/github.com/hashicorp/golang-lru/.golangci.yml
  vendor/github.com/hashicorp/golang-lru/2q.go
  vendor/github.com/hashicorp/golang-lru/LICENSE
  vendor/github.com/hashicorp/golang-lru/README.md
  vendor/github.com/hashicorp/golang-lru/arc.go
  vendor/github.com/hashicorp/golang-lru/doc.go
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/github.com/hashicorp/golang-lru/testing.go
  vendor/k8s.io/kubernetes/pkg/registry/core/secret/doc.go
  vendor/k8s.io/kubernetes/pkg/registry/core/secret/strategy.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#383 OCPBUGS-56474: Empty proxy variables are causing issues during the build
  pkg/build/controller/build/defaults/defaults.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
